//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaporUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depo
    {
        public string servisNo { get; set; }
        public string seriNo { get; set; }
        public string tarih { get; set; }
        public string model { get; set; }
        public string modelKodu { get; set; }
        public int ID { get; set; }
    }
}
