//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaporUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepoParca
    {
        public string depoID { get; set; }
        public string parcaAd { get; set; }
        public string parcaKod { get; set; }
        public string parcaDurum { get; set; }
        public int ID { get; set; }
    }
}
