//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaporUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteriHizmetleri
    {
        public Nullable<System.DateTime> tarih { get; set; }
        public string temsilci { get; set; }
        public string musteriAd { get; set; }
        public string musteriSoyad { get; set; }
        public string musteriTelefon { get; set; }
        public string musteriEmail { get; set; }
        public string musteriSikayeti { get; set; }
        public string musteriyeCevap { get; set; }
        public string musteriyeUlasildi { get; set; }
        public string cihazModel { get; set; }
        public string cihazSeriNo { get; set; }
        public int ID { get; set; }
    }
}
