//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaporUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raporlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Raporlar()
        {
            this.KullaniciRapor = new HashSet<KullaniciRapor>();
        }
    
        public string raporAdi { get; set; }
        public Nullable<System.DateTime> raporTarih { get; set; }
        public int ID { get; set; }
        public string kategori { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciRapor> KullaniciRapor { get; set; }
    }
}
