//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaporUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servis
    {
        public string servisNumarasi { get; set; }
        public string seriNumarasi { get; set; }
        public string model { get; set; }
        public string modelKodu { get; set; }
        public string musteriNo { get; set; }
        public string musteriAd { get; set; }
        public string musteriSoyad { get; set; }
        public string musteriAdres { get; set; }
        public string musteriIl { get; set; }
        public string musteriIlce { get; set; }
        public Nullable<System.DateTime> serviseGelisTarih { get; set; }
        public Nullable<System.DateTime> kargoTarihi { get; set; }
        public int ID { get; set; }
    }
}
